### ISSUE TITLE
calculated CRC16 ARC

### ISSUE THREAD

**Issue by yusmi25** [google/crclib.dart#11]
can I calculate the CRC16 ARC with this package
I have a data [0x0E 0x20 0xE0 0x07 0xA5 0x03 0x00 0x00 0x2E 0x46 0x49 0x54] and I want to calculate the CRC16
when I insert the data on the CRC Calculator the result is 0xA447
thanks..

**Comment by postmasters** [comment]
Yes. That function is available in the catalog. Please see https://github.com/google/crclib.dart/blob/fd1846793014c1b642c41f63a869bb04100e0cbd/lib/catalog.dart#L245.

**Comment by yusmi25** [comment]
can you create the example, because I don't understand how to use this
thank you..

**Comment by postmasters** [comment]
Something like this:

```dart
import 'package:crclib/catalog.dart';

Uint8List input = ...;
BigInt v = Crc16Arc().convert(input).toBigInt();
```

**Comment by yusmi25** [comment]
import 'package:crclib/crclib.dart';
import 'package:crclib/catalog.dart';

import 'package:crclib/catalog.dart';

void main() {
  List<int> input = [10, 20, 30];
  BigInt v = Crc16Arc().convert(input).toBigInt();
  print(v);
}


error on the toBigInt();

**Comment by postmasters** [comment]
I see. You are using the published package. In that case, you can call `toString`, or `toRadixString` to produce a String representation of the `CrcValue`. The method `toBigInt` is currently in `main` branch and not yet published via `pub`.

**Comment by yusmi25** [comment]
List<int> input = [14, 32, 224, 07, 165, 03, 00, 00, 46, 70, 73, 84];
print(Crc16Arc().convert(input).toRadixString(16)); // result a447
thank you it solve my problem :D
