### ISSUE TITLE
Does this package have Python crc_hqx function equivalent?

### ISSUE THREAD

**Issue by guyluz11** [google/crclib.dart#14]
I am trying to convert Python library to dart and I am not sure what the equivalent function for `crc_hqx` in this dependency.

Example from python 

```
binary_packet = 'fef052000232a1000000000034000100000000000000000013bb2e6100000000000000000000f0fe1c00000000000000000000000000000000000000000000000000000000000000000000000000'
or
binary_packet = [254, 240, 82, 0, 2, 50, 161, 0, 0, 0, 0, 0, 52, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 168, 187, 46, 97, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 240, 254, 28, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

result = crc_hqx(binary_packet, 0x1021);
// result will be 56902
```

**Comment by postmasters** [comment]
Perhaps `Crc16CcittTrue` is the right one? There are many Crc16 with polynomial of 0x1021. See https://reveng.sourceforge.io/crc-catalogue/16.htm. You may have to try each one of them until you find a match. I'm feeling lucky with that class though.

**Comment by guyluz11** [comment]
Tested all and didn't find it

![image](https://user-images.githubusercontent.com/9304740/131639391-479e2727-b2ab-4d73-bf0c-c32cecc01e24.png)
Did I missed something?.

**Comment by guyluz11** [comment]
[Source](https://docs.python.org/3/library/binascii.html) 
```
binascii.crc_hqx(data, value)

    Compute a 16-bit CRC value of data, starting with value as the initial CRC, and return the result. This uses the CRC-CCITT polynomial x16 + x12 + x5 + 1, often represented as 0x1021. This CRC is used in the binhex4 format.
```

I don't understand much about this, maybe it will help.

**Comment by postmasters** [comment]
```
>>> binary_packet = [254, 240, 82, 0, 2, 50, 161, 0, 0, 0, 0, 0, 52, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 168, 187, 46, 97, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 240, 254, 28, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
>>> data = bytes(binary_packet)
>>> import binascii
>>> binascii.crc_hqx(data, 0)
16372
```

So looks like `Crc16Xmodem` is the one?

**Comment by guyluz11** [comment]
I see now from your + my example that it is `Crc16Xmodem`/`Crc16Acorn`.

We are getting different results in python because you use `0` and I use `0x1021`

`binascii.crc_hqx(bytes(data), 0)`

`binascii.crc_hqx(bytes(binary_packet), 0x1021)`

I am not sure what is the name of the second parameter in my JavaScript example it is called previous.
So in this package by default it is using `0`, is there a way to change it?.

**Comment by postmasters** [comment]
You could change the `initialValue` of that class to `0x1021`, perhaps by subclassing? This is how it is currently defined.

```
class Crc16Xmodem extends ParametricCrc {
  Crc16Xmodem()
      : super(
          16,
          0x1021,
          0x0000,   // <--- initial value.
          0x0000,
          inputReflected: false,
          outputReflected: false);
}
```

**Comment by guyluz11** [comment]
Found it 

https://github.com/google/crclib.dart/blob/fd1846793014c1b642c41f63a869bb04100e0cbd/lib/catalog.dart#L617

If we change this to `0x1021` we get the 58817.

I can try to create pull request so that users will be able to change this value, tell me what you think.

**Comment by postmasters** [comment]
Normally initial values are either all 0s, or all 1s. For when you need a different initial value, subclassing `ParametricCrc` in your own code is more helpful, i.e. not meant for general population.

**Comment by guyluz11** [comment]
I have extended `ParametricCrc` with the new value

```
import 'package:crclib/crclib.dart';

class Crc16XmodemWith0x1021 extends ParametricCrc {
  Crc16XmodemWith0x1021()
      : super(16, 0x1021, 0x1021, 0x0000,
            inputReflected: false, outputReflected: false);
}
```

And now it works.

Thanks for all the help and support.
