### ISSUE TITLE
Does the lib support for CRC_16 [ISO3309]?

### ISSUE THREAD

**Issue by lts1610** [google/crclib.dart#7]
I found CRC_16 X25, but not sure that it following CRC_16 ISO3309. 

@davidmorgan  Please help me to confirm this.

**Comment by postmasters** [comment]
The best way to confirm it is what you need is to look at http://reveng.sourceforge.net/crc-catalogue/all.htm. This link is mentioned in the `README.md`.

**Comment by davidmorgan** [comment]
I have no connection to this project besides a minor bug fix, sorry!

**Comment by postmasters** [comment]
I just checked. ISO 13239 replaces ISO 3309. And ISO 13239 is Crc16X25.
